/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_caiquan_jni_JniDemo2 */

#ifndef _Included_com_caiquan_jni_JniDemo2
#define _Included_com_caiquan_jni_JniDemo2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_caiquan_jni_JniDemo2
 * Method:    compute
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_com_caiquan_jni_JniDemo2_compute
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
