/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_caiquan_jni_JniDemo */

#ifndef _Included_com_caiquan_jni_JniDemo
#define _Included_com_caiquan_jni_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_caiquan_jni_JniDemo
 * Method:    getLine
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_caiquan_jni_JniDemo_getLine
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
